### ISSUE TITLE
request: support travis-ci.com

### ISSUE THREAD

**Issue by skaji** [fayland/perl-Dist-Zilla-Plugin-GitHubREADME-Badge#34]
Now travis-ci.com supports  the GitHub Checks API, which is available to open source projects. 
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

It is nice if Dist-Zilla-Plugin-GitHubREADME-Badge also supports travis-ci.com badge.
(eg: https://travis-ci.com/skaji/Archive-Unpack)

**Comment by fayland** [comment]
do you have a sample badge URL for travis-ci.com? thanks

**Comment by skaji** [comment]
Here is a sample
```
[![Build Status](https://travis-ci.com/skaji/Archive-Unpack.svg?branch=master)](https://travis-ci.com/skaji/Archive-Unpack)
```

**Comment by fayland** [comment]
Hello. I made a

badges = travis-ci.com

and uploaded 0.27 to PAUSE. let me know if any problem.

Thanks

**Comment by skaji** [comment]
@fayland Thanks!!!
