### ISSUE TITLE
Kwalitee badge broken

### ISSUE THREAD

**Issue by kianmeng** [fayland/perl-Dist-Zilla-Plugin-GitHubREADME-Badge#35]
The Kwalitee badge is broken right now.
- Missing badge image.
![image](https://user-images.githubusercontent.com/134518/52179246-bbfdb700-2812-11e9-8108-050bab7dacd7.png)
- Incorrect link to CPANTS. Showing 'NOT FOUND' right now.
![image](https://user-images.githubusercontent.com/134518/52179261-d768c200-2812-11e9-9fd7-ecc7fb3273d3.png)

**Comment by fayland** [comment]
it's cpanauthors server problem. I'll recheck it later. thanks
