### ISSUE TITLE
Make branch name configurable

### ISSUE THREAD

**Issue by oalders** [fayland/perl-Dist-Zilla-Plugin-GitHubREADME-Badge#46]
First off, many thanks for this plugin. I use it in my author bundle. 😄 

Would it be possible to make the base branch name configurable? I now have a mixture of `master` and `main` among my repositories and for the GitHub Actions badge, it now looks broken for a new repo which does not have a `master` branch.

**Comment by fayland** [comment]
Sorry for delay. added
```
[GitHubREADME::Badge]
branch = main
```

hope it helps. Thanks

**Comment by oalders** [comment]
Thanks @fayland!
